config/routes.rb
Democracy::Application.routes.draw do
  devise_for :users

  resources :categories do
    resources :proposals do
      resources :comments
      resources :votes
    end
  end

  root :to => "dashboard#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :proposals

  validates_presence_of :name
  validates_numericality_of :expiry_seconds, :allow_nil => false
  validates_numericality_of :required_participation_percentage, :allow_nil => false
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :proposal
  belongs_to :user

  validates_presence_of :body
  validates_presence_of :proposal
  validates_presence_of :user
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  include ActiveRecord::Transitions
  
  belongs_to :category
  belongs_to :user
  has_many   :comments
  has_many   :votes
  
  validates_presence_of :category, :title, :description, :user
  before_create :set_expires_at
  
  state_machine do
    state :open
    state :closed
    
    event :close do
      transitions :from => :open, :to => :closed, :on_transition => :do_close
    end
  end
  
  default_scope order('id DESC')
  scope :state, lambda { |state| where('state = ?', state) }
  scope :accepted, where(:accepted => true)
  scope :rejected, where(:accepted => false)
  scope :expired,  where(['expires_at < ?', Time.now])
  
  def rejected?
    !accepted?
  end
  
  def expired?
    expires_at < Time.now
  end

  def required_participation
    (User.count * (category.required_participation_percentage / 100.0)).ceil
  end

protected

  def set_expires_at
    self.expires_at = Time.now + category.expiry_seconds
  end

  def do_close
    self.accepted  = votes.count >= required_participation && votes.in_favor.count > votes.count/2
    self.closed_at = Time.now
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :votes

  validates_presence_of :name
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :proposal
  belongs_to :user

  validates_presence_of :proposal
  validates_presence_of :user
  validates_inclusion_of  :value, :in => [-1, 1]
  validates_uniqueness_of :proposal_id, :scope => :user_id
  validate :proposal_state
  
  after_save :close_completed_proposal
  
  scope :against, where(:value => -1)
  scope :in_favor, where(:value => 1)

protected

  def proposal_state
    errors.add(:proposal, :not_open) if proposal && !proposal.open?
    errors.add(:proposal, :expired)  if proposal && proposal.expired?
  end
  
  def close_completed_proposal
    proposal.close! if proposal.votes.count == User.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  before_filter :authenticate_user!
  actions :create
  nested_belongs_to :category, :proposal
  
  def create
    @comment = parent.comments.new(params[:comment])
    @comment.user = current_user
    create! { parent_url }
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < InheritedResources::Base
  belongs_to :category
  actions :all, :except => [:edit, :update, :destroy]
  
  has_scope :state, :accepted, :rejected
  
  def show
    @proposal = parent.proposals.find(params[:id])
    @proposal.close! if @proposal.open? && @proposal.expired?
  end
  
  def create
    @proposal = parent.proposals.build(params[:proposal])
    @proposal.user = current_user
    create!
  end
  
protected

  def collection
    @proposals ||= end_of_association_chain.paginate(:page => params[:page])
  end
end

app/controllers/votes_controller.rb
class VotesController < InheritedResources::Base
  before_filter :authenticate_user!
  actions :create
  nested_belongs_to :category, :proposal
  
  def create
    @vote = parent.votes.build(params[:vote])
    @vote.user = current_user
    create!(:notice => t('controllers.votes.create.flash.notice')) do |format|
      format.html do
        unless @vote.errors.empty?
          flash[:alert] = @vote.errors.full_messages.unshift(t('controllers.votes.create.flash.alert')).join('. ')
        end
        redirect_to(parent_path)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.haml
.comment
  %em= t('controllers.proposals.comment.info', :user_name => comment.user.name, :comment_date => l(comment.created_at, :format => :short))
  = simple_format(comment.body)

app/views/layouts/_footer.html.haml
Referendum
= link_to(File.open(File.join(Rails.root, 'VERSION'), 'r').read, 'http://github.com/tigrish/referendum')

app/views/layouts/_messages.html.haml
= content_tag(:div, alert, :class => 'alert') if alert
= content_tag(:div, notice, :class => 'notice') if notice

app/views/layouts/_navigation.html.haml
%nav#navigation
  %ul
    - Category.all.each do |category|
      %li= link_to(category.name, category_proposals_path(category))

app/views/layouts/_user_session.html.haml
%nav#user_session
  %ul
    - if user_signed_in?
      %li= current_user.name
      %li= link_to(:profile, edit_user_registration_path)
      %li= link_to(:signout, destroy_user_session_path)
    - else
      %li= link_to(:sign_in, new_user_session_path)
      %li= link_to(:sign_up, new_user_registration_path)

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Referendum
    = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'compiled/print.css', :media => 'print'
    /[if lt IE 8]
      = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body{:class => content_for(:sidebar).blank? ? 'one-col' : 'two-col'}
    #header
      .container
        %logo#logo= link_to('Referendum', root_path)
        = render 'layouts/user_session'
        = render 'layouts/navigation'
    .container
      %section#content
        = render 'layouts/messages'
        = yield
      - unless content_for(:sidebar).blank?
        %section#sidebar= yield(:sidebar)
      %footer#footer= render 'layouts/footer'

app/views/proposals/_form.html.haml
= simple_form_for([@category, @proposal]) do |f|
  = f.input :title
  = f.input :description
  = f.submit

app/views/proposals/index.html.haml
%nav.tabs
  %ul
    %li= link_to('All',      category_proposals_path(@category))
    %li= link_to('open',     :state => :open)
    %li= link_to('accepted', :state => :closed, :accepted => true)
    %li= link_to('rejected', :state => :closed, :rejected => true)
    %li= link_to('Add',      new_category_proposal_path(@category))

%table
  %tr
    %th= Proposal.human_attribute_name(:id)
    %th= Proposal.human_attribute_name(:title)
    %th= Proposal.human_attribute_name(:user)
    %th= Proposal.human_attribute_name(:created_at)
    %th= Proposal.human_attribute_name(:state)
    %th= Proposal.human_attribute_name(:expires_at)
  - @proposals.each do |proposal|
    = content_tag_for(:tr, proposal) do
      %td= proposal.id
      %td= link_to(proposal.title, [@category, proposal])
      %td.user= proposal.user.name
      %td= l(proposal.created_at, :format => :short)
      %td.state{:class => proposal.state}= proposal.state
      %td= l(proposal.expires_at, :format => :short)

= will_paginate(@proposals)

app/views/proposals/new.html.haml
= render 'form'

app/views/proposals/show.html.haml
= content_tag_for(:section, @proposal) do
  %h1= @proposal.title
  %span.state{:class => @proposal.state}= @proposal.state
  %span.user= t('controllers.proposals.user.info', :user_name => @proposal.user.name, :proposal_date => l(@proposal.created_at, :format => :short))
  %span.expiry
    - if @proposal.expired?
      = t("controllers.proposals.expired", :date => l(@proposal.expires_at, :format => :short))
    - elsif @proposal.closed?
      = t("controllers.proposals.closed", :date => l(@proposal.closed_at, :format => :short))
    - else
      = t("controllers.proposals.expires", :date => l(@proposal.expires_at, :format => :short))
  %p= simple_format(@proposal.description)

%section#comments
  - if user_signed_in?
    = simple_form_for([@category, @proposal, Comment.new]) do |f|
      = f.input :body, :label => Comment.model_name.human, :input_html => { :rows => 5 }
      = f.submit :submit
  = render @proposal.comments
    
- content_for(:sidebar) do
  %section#votes
    .in_favor
      .wrapper
        .percentage
          = @proposal.votes.count == 0 ? number_to_percentage(0) : number_to_percentage((@proposal.votes.in_favor.count*100) / @proposal.votes.count)
        .count= t('controllers.proposals.votes.in_favor.count', :count => @proposal.votes.in_favor.count)
        
        - if user_signed_in? && !current_user.votes.where(:proposal_id => @proposal.id).any? && @proposal.open?
          = simple_form_for([@category, @proposal, Vote.new]) do |f|
            = f.input :value, :as => :hidden, :input_html => { :value => '1' }
            = f.submit t('controllers.proposals.votes.in_favor.action')
    .against
      .wrapper
        .percentage
          = @proposal.votes.count == 0 ? number_to_percentage(0) : number_to_percentage((@proposal.votes.against.count*100) / @proposal.votes.count)
        .count= t('controllers.proposals.votes.against.count', :count => @proposal.votes.against.count)

        - if user_signed_in? && !current_user.votes.where(:proposal_id => @proposal.id).any? && @proposal.open?
          = simple_form_for([@category, @proposal, Vote.new]) do |f|
            = f.input :value, :as => :hidden, :input_html => { :value => '-1' }
            = f.submit t('controllers.proposals.votes.against.action')

    %small= t('controllers.proposals.votes.total', :count => @proposal.votes.count)
    - if @proposal.open?
      %p= t('controllers.proposals.votes.needed', :count => @proposal.required_participation)
    - if user_signed_in? && current_user.votes.where(:proposal_id => @proposal.id).any?
      %p= t('controllers.proposals.votes.current_user_vote')